### ISSUE TITLE
Failed building wheel for pynini

### ISSUE THREAD

**Issue by Jiltseb** [ElementAI/build-pynini-wheels#5]
Hi,

I was looking to install pynini with dependencies in docker. Docker build gives me gcc error when building pynini wheels: 

error: command '/opt/rh/devtoolset-9/root/usr/bin/gcc' failed with exit code 1

ERROR: Failed building wheel for pynini

Am I missing something here? Any help is highly appreciated.

-Jilt S.

**Comment by kylebgorman** [comment]
Can you try the PR in #4? We're just trying to resolve copyright assignment there but we think it'll be the one we're using to generate wheels.

**Comment by Jiltseb** [comment]
Hi @kylebgorman, 

I confirm that I could generate wheels successfully. Thanks.

**Comment by PierreAndreNoel** [comment]
Closing this since #4 is now merged in master.
