### ISSUE TITLE
CLA

### ISSUE THREAD

**Issue by kylebgorman** [ElementAI/build-pynini-wheels#6]
I spoke with appropriate people at Google and if you can file the corporate CLA (https://cla.developers.google.com/about/google-corporate) we can proceed to incorporate this.

**Comment by kylebgorman** [comment]
Gentle ping @PierreAndreNoel. I uploaded the wheels for 2.1.4 to PyPI but I'd like to ship this with Pynini itself too.

**Comment by PierreAndreNoel** [comment]
Hello @kylebgorman . Thanks for the ping, I didn't see your issue before today. Starting the process on my side now.

**Comment by PierreAndreNoel** [comment]
@kylebgorman ServiceNow already signed this CLA on April 16th 2021 and, from what I understand, this could have effect corporation wide. Could you please check on your side?

**Comment by kylebgorman** [comment]
Great, verified.

Let me suggest: leave this repo up until the next Pynini release, in case anyone wants to (e.g.) adding stripping to the SOs. Once the next release is out and on GitHub I can accept PRs (at least to the Dockerfile) there.

**Comment by PierreAndreNoel** [comment]
Ok no problem, I'm leaving the repo up. If/when further action is required, please do not hesitate to tag me personally.
